enum {
	CHAR_DEV_IOCTL_GET_DEV_INFO = 0,
	CHAR_DEV_IOCTL_SET_DEV_INFO,
	CHAR_DEV_IOCTL_SET_GET_DEV_INFO,
	CHAR_DEV_IOCTL_MAX,
};


#define	CHAR_DEV_IOCTL_MAGIC	(0x5D)

#define GET_DEV_INFO	_IOR(CHAR_DEV_IOCTL_MAGIC, \
			     CHAR_DEV_IOCTL_GET_DEV_INFO, int)

#define	SET_DEV_INFO	_IOW(CHAR_DEV_IOCTL_MAGIC, \
			     CHAR_DEV_IOCTL_SET_DEV_INFO, int)

#define	SET_GET_DEV_INFO	_IOWR(CHAR_DEV_IOCTL_MAGIC, \
				      CHAR_DEV_IOCTL_SET_GET_DEV_INFO, int)
